"""C_9_16-3-1_2

Revision ID: 5b9b6252603e
Revises: bb40daf93e53
Create Date: 2016-03-01 16:19:21.131970

"""

# revision identifiers, used by Alembic.
revision = '5b9b6252603e'
down_revision = 'bb40daf93e53'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_roles_default'), 'roles', ['default'], unique=False)
    op.drop_index('default', table_name='roles')
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_index('default', 'roles', ['default'], unique=True)
    op.drop_index(op.f('ix_roles_default'), table_name='roles')
    ### end Alembic commands ###
