"""C_3-24_12.2_update_data

Revision ID: 6c5e7b1bfd8a
Revises: be469a37119c
Create Date: 2016-03-24 15:11:21.396397

"""

# revision identifiers, used by Alembic.
revision = '6c5e7b1bfd8a'
down_revision = 'be469a37119c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'follows', 'users', ['follower_id'], ['id'])
    op.create_foreign_key(None, 'follows', 'users', ['followed_id'], ['id'])
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    op.drop_constraint(None, 'follows', type_='foreignkey')
    ### end Alembic commands ###
