"""C_8-2-16

Revision ID: b70ac5deebbf
Revises: c9c1ca205749
Create Date: 2016-02-16 11:31:38.381571

"""

# revision identifiers, used by Alembic.
revision = 'b70ac5deebbf'
down_revision = 'c9c1ca205749'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'confirmed')
    ### end Alembic commands ###
