"""C9_16_3_1

Revision ID: bb40daf93e53
Revises: b70ac5deebbf
Create Date: 2016-03-01 14:04:21.650853

"""

# revision identifiers, used by Alembic.
revision = 'bb40daf93e53'
down_revision = 'b70ac5deebbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('default', sa.Boolean(), nullable=True))
    op.add_column('roles', sa.Column('permission', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'roles', ['default'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_column('roles', 'permission')
    op.drop_column('roles', 'default')
    ### end Alembic commands ###
