"""C_3-23_12.1

Revision ID: be469a37119c
Revises: f8cdc1a2d8a3
Create Date: 2016-03-23 15:35:32.221472

"""

# revision identifiers, used by Alembic.
revision = 'be469a37119c'
down_revision = 'f8cdc1a2d8a3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follows',
    sa.Column('follower_id', sa.Integer(), nullable=False),
    sa.Column('followed_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('follower_id', 'followed_id')
    )
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'students', ['student_id'], ['id'])
    op.create_foreign_key(None, 'registrations', 'classes', ['class_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'registrations', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_table('follows')
    ### end Alembic commands ###
