"""C_11.4_3.15_2

Revision ID: f5cf2b3daae9
Revises: 3dc53c84970a
Create Date: 2016-03-15 11:11:03.301554

"""

# revision identifiers, used by Alembic.
revision = 'f5cf2b3daae9'
down_revision = '3dc53c84970a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'])
    op.create_foreign_key(None, 'users', 'roles', ['role_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'body_html')
    ### end Alembic commands ###
